### ISSUE TITLE
progress issue

### ISSUE THREAD

**Issue by gluttm** [segnolin/google-drive-folder-downloader#2]
the script Rocks, work like a charm , I never worked with Gdrive API, and i'm Python leaner is there any easier way to show progress or like some verbose mode...

**Comment by segnolin** [comment]
Thanks for using this script!

There is actually a progress for each download, but it looks like it jumps straight to 100% because the chunk size for the download is greater than the file size. The chunk size for this script is 1 GB, which can be found from `MediaIoBaseDownload(fh, request, 1024 * 1024 * 1024)`, so unless the file size is over 1 GB, the progress will always jump to 100% once it's finished.

I set the chunk size so large because I don't want too many overheads for the download (the initialization for each chunk takes time). If you really want to see the progress more often, you can set the chunk size smaller, like `MediaIoBaseDownload(fh, request, 1024 * 1024)` for 1 MB chunk size, but it would be inefficient when downloading large file.

I might add the option to set the chunk size in the future updates.

Hope this help!

**Comment by gluttm** [comment]
well, it helps, and your are right about keeping 1 GB, when it comes to large files 1 MB doesn't help.

thanks for the script, please keep improving it, more options would help

**Comment by segnolin** [comment]
Sure.
