### ISSUE TITLE
ModuleNotFoundError: No module named 'googleapiclient'

### ISSUE THREAD

**Issue by agonen** [segnolin/google-drive-folder-downloader#6]
Traceback (most recent call last):
  File "download.py", line 1, in <module>
    from googleapiclient.http import MediaIoBaseDownload
ModuleNotFoundError: No module named 'googleapiclient'

add in readme 
pip  install  google-api-python-client

**Comment by segnolin** [comment]
Thank you for the suggestion!

In my "Getting Started" section, I put the Quickstart link, which has all the information about how to use the google drive api, including the pip commands.

Because the requirement of using this script is not only installing the google-api-python-client module, I think everyone who wants to run the script needs to dive into the Quickstart page. There are many steps to do like enabling the drive api of your google account, acquiring credential file, and you also need the link provided in the Quickstart page to do so.
